### ISSUE TITLE
Determine the application environment and/or framework that will be used to implement the portal

### ISSUE THREAD

**Issue by patbarron** [wplug/MemberPortal#7]
The leading candidate in our informal discussions up to now seems to be raw, unadorned PHP.  But there are some other choices, which we should probably at least document (maybe with a few words about why they are or are not desirable for this project).

Potential other choices:
- CGI (shell) scripting.  This might be interesting to try to use to put together a quick prototype, but I think it would be too cumbersome (and perhaps too prone to security issues, if we're not careful) to use "for real".
- Java (using an app server environment like Tomcat or something) - this would give us easy facilities for things like database abstraction (see issue #6), but there's an awful lot of infrastructure that would need to be deployed to support it, and I am not sure to what extent any of us are J2EE programmers...  So probably not.
- Rails - It's truly built for apps exactly like this, and there are prepackaged toolkits for dealing with services like Stripe (though that's available for raw PHP, as well).  But it also requires some infrastructure that we'd need to maintain (and that really would need to be maintained outside of the package system on the VPS, because the packaged Rails versions in mainstream distros are really far behind the times, and most of the tools (like "gem") kind of expect to be able to maintain stuff outside of the OS anyway.  We also may be somewhat limited in Ruby skills.  Perhaps worth giving some consideration to, but may just be overkill.
- Node.js - maybe a possibility, but I personally don't know enough about it to understand if we should really consider it or not.

Others?

**Comment by jprostko** [comment]
We should definitely consider PHP frameworks which essentially can just be used once their code is dropped into place.  The most prevalent one nowadays in projects I follow is Symfony, but there's other ones like CodeIgniter, Laravel, CakePHP, Zend, and Yii.  I recall using Yii in the past somewhat, since the last time I explored it, it seemed to be the most feature-rich and up-to-date framework at that time.  I'll probably have to try a few and compare them to the above non-PHP suggestions.

**Comment by lazypower** [comment]
I think we need to have a good touch on what our contributor patterns would look like in order to make this call. If we have anyone in the group that has the time to work in something outside of PHP - lets see how quickly we can prototype it in Rails/Pyramid.  If the majority of expertise in house is PHP - lets stick with PHP.

I'm familiar in PHP, Rails, Python, and .Net - so there are my 4 patterns of choice, and I can contribute as time comes available. I'm always up for some Coding For Fun.

**Comment by jprostko** [comment]
I am most familiar with PHP, then Python.  I have done some .NET over the years, but admit I don't have much interest utilizing that or Ruby based on my preferences and previous experiences.

That said, if somebody can throw something together fast in RoR, I wouldn't hold that person back and would likely jump in to help.  I'm just stating that I tend to have my preferences, and in this case, it's mostly PHP and Python.  :)

PHP always makes the most sense to me since it's pretty much always installed on a web server, and I don't really like adding extra software to the stack if I don't have to.

I'll be the first to admit that I haven't even played with Node.JS, nor any Java application servers.  If somebody does though, we can certainly explore those avenues as well.

**Comment by jprostko** [comment]
I have been getting acquainted with the developer version of Laravel 5 the past few weeks, and seeing as it is officially released as of today, I'm going to spend more time with it, if only for my benefit.  I already got some basic code done locally to integrate with Stripe, and that should be able to be used for the member portal with little or no modifications.  I still want to make it a bit more general purpose (I was mostly just "finding a problem to solve" to help me learn), so that other payment options can be added or removed easily.  That said, we still need to bear down on further requirements, so I'll wait until we are sure the work I have done is congruent with our goals before considering pushing anything to the repo.

As of now I'd like to proceed with PHP/Laravel, but again, I am open to other technologies if people involved want to use something else.  That said, at the moment it's just a few of us, so it may just make sense to proceed using Laravel if there is no outright objection to using it.

**Comment by jprostko** [comment]
Somehow I missed Laravel's Cashier while I was starting to learn Laravel.  It seems it only works with Stripe though as it is implemented, which is unfortunate.  I would think it could be extended to handle other payment processors though.

http://laravel.com/docs/master/billing

If not, something like this could be pulled in, or a custom solution could be done:

https://github.com/thephpleague/omnipay

Anyway, I will keep track of the various viable options as I come across them.

**Comment by patbarron** [comment]
Closing this issue, as WPLUG (as an organization) is currently defunct, and this project has been abandoned.
